//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public System.Guid AccountID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string AccountNameEnglish { get; set; }
        public string Description { get; set; }
        public Nullable<int> Grade { get; set; }
        public bool IsParent { get; set; }
        public int AccountCategoryKind { get; set; }
        public bool Active { get; set; }
    }
}
