//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountObjectBankAccount
    {
        public System.Guid AccountObjectBankAccountID { get; set; }
        public System.Guid AccountObjectID { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string Description { get; set; }
        public int Active { get; set; }
    }
}
