//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public System.Guid BranchID { get; set; }
        public Nullable<System.Guid> BranchTypeID { get; set; }
        public Nullable<System.Guid> BankAccountID { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public bool IsHeadQuarters { get; set; }
        public string Address { get; set; }
        public string CompanyTaxCode { get; set; }
        public string CompanyTel { get; set; }
        public string CompanyFax { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyWebsite { get; set; }
        public string DirectorTitle { get; set; }
        public string DirectorName { get; set; }
        public string ChiefOfAccountingTitle { get; set; }
        public string ChiefOfAccountingName { get; set; }
        public string LocationTile { get; set; }
        public string LocationName { get; set; }
        public string CashierTitle { get; set; }
        public string CashierName { get; set; }
        public string ReporterTitle { get; set; }
        public string ReporterName { get; set; }
        public bool Active { get; set; }
    }
}
