//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEADERDELIVERY39668C965069455DAC584186C942B8F1
    {
        public System.Guid VoucherID { get; set; }
        public string VoucherNO { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<System.Guid> Customer { get; set; }
        public string Address { get; set; }
        public string ContactName { get; set; }
        public string Description { get; set; }
    }
}
