//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class INOutwardDetail
    {
        public System.Guid VoucherDetailID { get; set; }
        public System.Guid VoucherID { get; set; }
        public System.Guid ProductID { get; set; }
        public string Description { get; set; }
        public System.Guid LocationID { get; set; }
        public string DebitAccount { get; set; }
        public string CreditAccount { get; set; }
        public System.Guid UOMID { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
