//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string Id { get; set; }
        public string GroupId { get; set; }
        public string Caption { get; set; }
        public string Icon { get; set; }
        public string Tag { get; set; }
        public Nullable<bool> Default { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Level { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
