//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeveloverEntities : DbContext
    {
        public DeveloverEntities()
            : base("name=DeveloverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> SysDELListVoucher { get; set; }
        public virtual DbSet<AccountObject> AccountObjects { get; set; }
        public virtual DbSet<AccountObjectBankAccount> AccountObjectBankAccounts { get; set; }
        public virtual DbSet<AccountObjectGroup> AccountObjectGroups { get; set; }
        public virtual DbSet<AccountTransfer> AccountTransfers { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BranchType> BranchTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveryDetail> DeliveryDetails { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product1> Product1 { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<SchedulerAppointment> SchedulerAppointments { get; set; }
        public virtual DbSet<SchedulerResource> SchedulerResources { get; set; }
        public virtual DbSet<SchedulerTaskDependency> SchedulerTaskDependencies { get; set; }
        public virtual DbSet<sysDELGridColumn> sysDELGridColumns { get; set; }
        public virtual DbSet<sysDELGroupUser> sysDELGroupUsers { get; set; }
        public virtual DbSet<SysDELHistoryLogin> SysDELHistoryLogins { get; set; }
        public virtual DbSet<SysDELListVoucher> SysDELListVouchers { get; set; }
        public virtual DbSet<sysDELOption> sysDELOptions { get; set; }
        public virtual DbSet<sysDELUser> sysDELUsers { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<Vender> Venders { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<AccountHistory> AccountHistories { get; set; }
        public virtual DbSet<AccountObjectBankAccountHistory> AccountObjectBankAccountHistories { get; set; }
        public virtual DbSet<AccountObjectGroupHistory> AccountObjectGroupHistories { get; set; }
        public virtual DbSet<AccountObjectHistory> AccountObjectHistories { get; set; }
        public virtual DbSet<AccountTransferHistory> AccountTransferHistories { get; set; }
        public virtual DbSet<BADeposit> BADeposits { get; set; }
        public virtual DbSet<BADepositDetail> BADepositDetails { get; set; }
        public virtual DbSet<BankAccountHistory> BankAccountHistories { get; set; }
        public virtual DbSet<BAWithDraw> BAWithDraws { get; set; }
        public virtual DbSet<BAWithDrawDetail> BAWithDrawDetails { get; set; }
        public virtual DbSet<BranchHistory> BranchHistories { get; set; }
        public virtual DbSet<BranchTypeHistory> BranchTypeHistories { get; set; }
        public virtual DbSet<CAPayment> CAPayments { get; set; }
        public virtual DbSet<CAPaymentDetail> CAPaymentDetails { get; set; }
        public virtual DbSet<CAReceipt> CAReceipts { get; set; }
        public virtual DbSet<CAReceiptDetail> CAReceiptDetails { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<grid> grids { get; set; }
        public virtual DbSet<HEADERDELIVERY21C77654CD904F4685515946D5E3ACFC> HEADERDELIVERY21C77654CD904F4685515946D5E3ACFC { get; set; }
        public virtual DbSet<HEADERDELIVERY39668C965069455DAC584186C942B8F1> HEADERDELIVERY39668C965069455DAC584186C942B8F1 { get; set; }
        public virtual DbSet<HEADERDELIVERY52E31404701A47A0A9514573C7BBB3FF> HEADERDELIVERY52E31404701A47A0A9514573C7BBB3FF { get; set; }
        public virtual DbSet<INInward> INInwards { get; set; }
        public virtual DbSet<INInwardDetail> INInwardDetails { get; set; }
        public virtual DbSet<INOutward> INOutwards { get; set; }
        public virtual DbSet<INOutwardDetail> INOutwardDetails { get; set; }
        public virtual DbSet<INTransfer> INTransfers { get; set; }
        public virtual DbSet<INTransferDetail> INTransferDetails { get; set; }
        public virtual DbSet<LocationHistory> LocationHistories { get; set; }
        public virtual DbSet<ProductHistory> ProductHistories { get; set; }
        public virtual DbSet<ProductTypeHistory> ProductTypeHistories { get; set; }
        public virtual DbSet<PUReturn> PUReturns { get; set; }
        public virtual DbSet<PUReturnDetail> PUReturnDetails { get; set; }
        public virtual DbSet<PUVoucher> PUVouchers { get; set; }
        public virtual DbSet<PUVoucherDetail> PUVoucherDetails { get; set; }
        public virtual DbSet<SAReturn> SAReturns { get; set; }
        public virtual DbSet<SAReturnDetail> SAReturnDetails { get; set; }
        public virtual DbSet<SAVoucher> SAVouchers { get; set; }
        public virtual DbSet<SAVoucherDetail> SAVoucherDetails { get; set; }
        public virtual DbSet<UOMHistory> UOMHistories { get; set; }
        public virtual DbSet<VDelivery> VDeliveries { get; set; }
        public virtual DbSet<VDeliverySearch> VDeliverySearches { get; set; }
        public virtual DbSet<VProduct> VProducts { get; set; }
        public virtual DbSet<VSysDELHistoryLogin> VSysDELHistoryLogins { get; set; }
    }
}
