//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product1
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public string Name { get; set; }
        public Nullable<int> UOMId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Origin { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public string Detail { get; set; }
        public byte[] Picture { get; set; }
        public string SKU { get; set; }
        public string AlterNote { get; set; }
        public Nullable<int> DefaultLocationId { get; set; }
    }
}
