//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAVoucherDetail
    {
        public System.Guid VoucherDetailID { get; set; }
        public System.Guid VoucherID { get; set; }
        public System.Guid ProductID { get; set; }
        public string Description { get; set; }
        public string DebitAccount { get; set; }
        public string CreditAccount { get; set; }
        public Nullable<System.Guid> OUMID { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal UnitPriceAfterTax { get; set; }
        public decimal AmountForeignCurrency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal DiscountRate { get; set; }
        public decimal DiscountAmountForeignCurrency { get; set; }
        public decimal DiscountAmount { get; set; }
        public string DiscountAccount { get; set; }
        public Nullable<decimal> VATRate { get; set; }
        public decimal VATAmountOC { get; set; }
        public decimal VATAmount { get; set; }
        public string VATAccount { get; set; }
        public int SortOrder { get; set; }
        public string VATDescription { get; set; }
        public Nullable<System.Guid> AccountObjectID { get; set; }
        public string AccountObjectName { get; set; }
        public string AccountObjectAddress { get; set; }
    }
}
