//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysDELOption
    {
        public int ID { get; set; }
        public string CodePersonal { get; set; }
        public string Name { get; set; }
        public string Acronym { get; set; }
        public string Address { get; set; }
        public string NameDirector { get; set; }
        public string MobilePhone { get; set; }
        public string Landline { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
    }
}
