//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysDELGroupUser
    {
        public System.Guid ID { get; set; }
        public string NameGroup { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
