//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysDELGridColumn
    {
        public string Model { get; set; }
        public string Name { get; set; }
        public string Caption { get; set; }
        public string Type { get; set; }
        public byte Width { get; set; }
        public string ChildModel { get; set; }
        public string KeyMember { get; set; }
        public string ValueMember { get; set; }
        public string DisplayMember { get; set; }
        public string NullText { get; set; }
        public string DataSource { get; set; }
        public byte OrderNo { get; set; }
        public string SumaryType { get; set; }
        public string StringFormat { get; set; }
        public bool AllowFocus { get; set; }
        public bool AllowEdit { get; set; }
        public bool Visible { get; set; }
    }
}
