//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public System.Guid VendorID { get; set; }
        public string VendorName { get; set; }
        public string TaxCode { get; set; }
        public string Address { get; set; }
        public string ContactName { get; set; }
        public string FaxNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string LandlineNumber { get; set; }
        public string Email { get; set; }
        public string BankNo { get; set; }
        public string AccountHolder { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string SWIFTCode { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
