//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develover.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProduct
    {
        public System.Guid ProductID { get; set; }
        public Nullable<System.Guid> UOMID { get; set; }
        public Nullable<System.Guid> LocationID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Model { get; set; }
        public string Origin { get; set; }
        public decimal QualityMin { get; set; }
        public decimal QualityMax { get; set; }
        public Nullable<System.Guid> UOMSize { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<System.Guid> UOMWeight { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string UOMName { get; set; }
        public string UOMSizeName { get; set; }
        public string UOMWeigthName { get; set; }
        public string LocationName { get; set; }
    }
}
