//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeveloverWarehouse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public byte Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public string Default { get; set; }
        public bool System { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
